# Generated by Django 4.2.27 on 2026-01-26 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, help_text='SMTP服务器地址，如smtp.gmail.com', max_length=255, null=True, verbose_name='SMTP服务器')),
                ('smtp_port', models.IntegerField(blank=True, help_text='SMTP服务器端口，通常为587或465', null=True, verbose_name='SMTP端口')),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='是否使用TLS加密连接', verbose_name='使用TLS')),
                ('smtp_username', models.CharField(blank=True, help_text='SMTP登录用户名，通常是邮箱地址', max_length=255, null=True, verbose_name='SMTP用户名')),
                ('smtp_password', models.CharField(blank=True, help_text='SMTP登录密码或应用专用密码', max_length=255, null=True, verbose_name='SMTP密码')),
                ('smtp_from_email', models.EmailField(blank=True, help_text='系统发送邮件时使用的发件人地址', max_length=254, null=True, verbose_name='发件人邮箱')),
                ('captcha_id', models.CharField(blank=True, help_text='验证码服务的公共ID（Geetest的captcha_id 或 Turnstile的site key）', max_length=255, null=True, verbose_name='验证码 ID')),
                ('captcha_key', models.CharField(blank=True, help_text='验证码服务的密钥（Geetest的private_key 或 Turnstile的secret key）', max_length=255, null=True, verbose_name='验证码密钥')),
                ('captcha_provider', models.CharField(choices=[('none', '无'), ('geetest', 'Geetest (极验 v4)'), ('turnstile', 'Cloudflare Turnstile'), ('local', '本地图片验证码')], default='none', help_text='选择要启用的验证码提供器（只能选择其一）', max_length=32, verbose_name='验证码提供器')),
                ('email_captcha_provider', models.CharField(blank=True, choices=[('none', '无'), ('geetest', 'Geetest (极验 v4)'), ('turnstile', 'Cloudflare Turnstile'), ('local', '本地图片验证码')], help_text='邮箱场景的验证码提供器（留空则使用全局配置）', max_length=32, null=True, verbose_name='邮箱验证码提供器')),
                ('email_captcha_id', models.CharField(blank=True, help_text='邮箱场景验证码服务的公共ID（如果为空，则使用全局配置）', max_length=255, null=True, verbose_name='邮箱验证码 ID')),
                ('email_captcha_key', models.CharField(blank=True, help_text='邮箱场景验证码服务的密钥（如果为空，则使用全局配置）', max_length=255, null=True, verbose_name='邮箱验证码密钥')),
                ('login_captcha_provider', models.CharField(blank=True, choices=[('none', '无'), ('geetest', 'Geetest (极验 v4)'), ('turnstile', 'Cloudflare Turnstile'), ('local', '本地图片验证码')], help_text='登录场景的验证码提供器（留空则使用全局配置）', max_length=32, null=True, verbose_name='登录验证码提供器')),
                ('login_captcha_id', models.CharField(blank=True, help_text='登录场景验证码服务的公共ID（如果为空，则使用全局配置）', max_length=255, null=True, verbose_name='登录验证码 ID')),
                ('login_captcha_key', models.CharField(blank=True, help_text='登录场景验证码服务的密钥（如果为空，则使用全局配置）', max_length=255, null=True, verbose_name='登录验证码密钥')),
                ('register_captcha_provider', models.CharField(blank=True, choices=[('none', '无'), ('geetest', 'Geetest (极验 v4)'), ('turnstile', 'Cloudflare Turnstile'), ('local', '本地图片验证码')], help_text='注册场景的验证码提供器（留空则使用全局配置）', max_length=32, null=True, verbose_name='注册验证码提供器')),
                ('register_captcha_id', models.CharField(blank=True, help_text='注册场景验证码服务的公共ID（如果为空，则使用全局配置）', max_length=255, null=True, verbose_name='注册验证码 ID')),
                ('register_captcha_key', models.CharField(blank=True, help_text='注册场景验证码服务的密钥（如果为空，则使用全局配置）', max_length=255, null=True, verbose_name='注册验证码密钥')),
                ('site_name', models.CharField(default='ZASCA', help_text='系统显示的站点名称', max_length=100, verbose_name='站点名称')),
                ('enable_registration', models.BooleanField(default=False, help_text='是否开启用户注册功能，默认为关闭', verbose_name='启用用户注册')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_type', models.CharField(choices=[('user_count', '用户数量'), ('host_count', '主机数量'), ('operation_count', '操作数量'), ('active_host_count', '活跃主机数'), ('error_count', '错误数量')], help_text='统计数据的类型', max_length=50, verbose_name='统计类型')),
                ('stats_value', models.IntegerField(help_text='统计数据的值', verbose_name='统计值')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='统计数据创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统统计',
                'verbose_name_plural': '系统统计',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stats_type'], name='dashboard_s_stats_t_d000e0_idx'), models.Index(fields=['created_at'], name='dashboard_s_created_068de5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('stat_card', '统计卡片'), ('chart', '图表'), ('recent_operations', '最近操作'), ('host_status', '主机状态'), ('system_alerts', '系统告警')], help_text='组件的类型', max_length=50, verbose_name='组件类型')),
                ('title', models.CharField(help_text='组件显示的标题', max_length=200, verbose_name='标题')),
                ('display_order', models.IntegerField(default=0, help_text='组件在仪表盘上的显示顺序', verbose_name='显示顺序')),
                ('is_enabled', models.BooleanField(default=True, help_text='组件是否在仪表盘上显示', verbose_name='是否启用')),
                ('widget_config', models.JSONField(blank=True, default=dict, help_text='组件的配置参数', verbose_name='组件配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='组件创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='组件更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仪表盘组件',
                'verbose_name_plural': '仪表盘组件',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['widget_type'], name='dashboard_d_widget__357338_idx'), models.Index(fields=['is_enabled'], name='dashboard_d_is_enab_79f78f_idx'), models.Index(fields=['display_order'], name='dashboard_d_display_5437b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text='用户活动的类型', max_length=100, verbose_name='活动类型')),
                ('description', models.TextField(blank=True, help_text='活动描述', verbose_name='描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='用户操作的IP地址', null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, help_text='用户浏览器的User-Agent信息', verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='活动记录创建时间', verbose_name='创建时间')),
                ('user', models.ForeignKey(help_text='关联的用户', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户活动',
                'verbose_name_plural': '用户活动',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='dashboard_u_user_id_00b481_idx'), models.Index(fields=['activity_type'], name='dashboard_u_activit_a0fab2_idx'), models.Index(fields=['ip_address'], name='dashboard_u_ip_addr_76ce0f_idx'), models.Index(fields=['created_at'], name='dashboard_u_created_8f7e1e_idx')],
            },
        ),
    ]
