# Generated by Django 4.2.27 on 2026-01-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='email_suffix_list',
            field=models.TextField(blank=True, help_text='允许或禁止的邮箱后缀列表，每行一个后缀，例如：\n@example.com\n@gmail.com\n@company.com', null=True, verbose_name='邮箱后缀列表'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='email_suffix_mode',
            field=models.CharField(choices=[('allow_all', '全部允许'), ('whitelist', '白名单'), ('blacklist', '黑名单')], default='allow_all', help_text='邮箱后缀验证模式：全部允许、白名单或黑名单', max_length=20, verbose_name='邮箱后缀模式'),
        ),
    ]
