# Generated by Django 4.2.27 on 2026-05-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_add_local_access_locked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
