# Generated by Django 4.2.27 on 2026-05-02 09:05

from django.db import migrations, models


def migrate_email_suffix_data(apps, schema_editor):
    SystemConfig = apps.get_model('dashboard', 'SystemConfig')
    for config in SystemConfig.objects.all():
        old_mode = getattr(config, 'email_suffix_mode', None)
        old_list = getattr(config, 'email_suffix_list', None) or ''
        if old_mode == 'whitelist' and old_list.strip():
            config.email_suffix_whitelist = old_list
            config.email_suffix_blacklist = ''
        elif old_mode == 'blacklist' and old_list.strip():
            config.email_suffix_whitelist = ''
            config.email_suffix_blacklist = old_list
        else:
            config.email_suffix_whitelist = ''
            config.email_suffix_blacklist = ''
        config.save(update_fields=['email_suffix_whitelist', 'email_suffix_blacklist'])


def reverse_migrate_email_suffix_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='email_suffix_blacklist',
            field=models.TextField(blank=True, help_text='禁止注册的邮箱后缀列表，每行一个后缀，例如：\n@tempmail.com\n@spam.com\n留空表示不限制', null=True, verbose_name='邮箱后缀黑名单'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='email_suffix_whitelist',
            field=models.TextField(blank=True, help_text='允许注册的邮箱后缀列表，每行一个后缀，例如：\n@example.com\n@gmail.com\n@company.com\n留空表示不限制', null=True, verbose_name='邮箱后缀白名单'),
        ),
        migrations.RunPython(migrate_email_suffix_data, reverse_migrate_email_suffix_data),
        migrations.RemoveField(
            model_name='systemconfig',
            name='email_suffix_list',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='email_suffix_mode',
        ),
    ]
