# Generated by Django 4.2.27 on 2026-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_systemconfig_email_suffix_whitelist_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='qq_bot_host',
            field=models.CharField(blank=True, help_text='QQ机器人服务器的主机地址（系统默认配置）', max_length=255, null=True, verbose_name='QQ机器人服务器地址'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='qq_bot_port',
            field=models.CharField(blank=True, help_text='QQ机器人服务器的端口号（系统默认配置）', max_length=20, null=True, verbose_name='QQ机器人服务器端口'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='qq_bot_token',
            field=models.CharField(blank=True, help_text='用于认证的访问令牌（系统默认配置）', max_length=255, null=True, verbose_name='QQ机器人访问令牌'),
        ),
    ]
