# Generated by Django 4.2.27 on 2026-05-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_qq_bot_default_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='qq_bot_host',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='qq_bot_port',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='qq_bot_token',
        ),
    ]
