# Generated by Django 4.2.27 on 2026-02-01 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='任务ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='任务结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='目标对象ID')),
                ('target_content_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='目标对象类型')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '异步任务',
                'verbose_name_plural': '异步任务',
                'db_table': 'async_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(verbose_name='进度百分比')),
                ('message', models.TextField(blank=True, null=True, verbose_name='进度消息')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='tasks.asynctask')),
            ],
            options={
                'verbose_name': '任务进度',
                'verbose_name_plural': '任务进度',
                'db_table': 'task_progress',
                'ordering': ['-timestamp'],
            },
        ),
    ]
