# Generated by Django 4.2.27 on 2026-01-26 03:24

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, help_text='用户的手机号码', max_length=20, null=True, verbose_name='手机号码')),
                ('avatar', models.ImageField(blank=True, help_text='用户头像图片', null=True, upload_to='avatars/', verbose_name='头像')),
                ('is_verified', models.BooleanField(default=False, help_text='用户邮箱是否已验证', verbose_name='已验证')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='用户最后一次登录的IP地址', null=True, verbose_name='最后登录IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='用户账号创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='用户信息最后更新时间', verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='用户昵称', max_length=50, verbose_name='昵称')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], help_text='用户性别', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, help_text='用户生日', null=True, verbose_name='生日')),
                ('location', models.CharField(blank=True, help_text='用户所在地', max_length=100, verbose_name='所在地')),
                ('bio', models.TextField(blank=True, help_text='用户个人简介', verbose_name='个人简介')),
                ('email_notification', models.BooleanField(default=True, help_text='是否接收邮件通知', verbose_name='邮件通知')),
                ('system_notification', models.BooleanField(default=True, help_text='是否接收系统通知', verbose_name='系统通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='资料创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='资料最后更新时间', verbose_name='更新时间')),
                ('user', models.OneToOneField(help_text='关联的用户', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='登录时的IP地址', verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, help_text='登录时的浏览器信息', verbose_name='用户代理')),
                ('login_type', models.CharField(choices=[('web', '网页登录'), ('api', 'API登录'), ('other', '其他')], default='web', help_text='用户的登录方式', max_length=20, verbose_name='登录方式')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], help_text='登录是否成功', max_length=20, verbose_name='登录状态')),
                ('failure_reason', models.CharField(blank=True, help_text='登录失败的原因', max_length=200, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='登录发生的时间', verbose_name='登录时间')),
                ('user', models.ForeignKey(help_text='登录的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='accounts_lo_user_id_20fa14_idx'), models.Index(fields=['ip_address'], name='accounts_lo_ip_addr_51fef5_idx'), models.Index(fields=['status'], name='accounts_lo_status_0f4a4d_idx'), models.Index(fields=['created_at'], name='accounts_lo_created_6efabd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='accounts_us_phone_f54457_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
    ]
