# Generated by Django 4.2.27 on 2026-05-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='默认组不可删除，系统预设角色', verbose_name='默认组')),
                ('description', models.TextField(blank=True, help_text='用户组的功能描述', verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, help_text='数值越小排序越靠前', verbose_name='排序')),
                ('group', models.OneToOneField(help_text='关联的Django用户组', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group', verbose_name='用户组')),
            ],
            options={
                'verbose_name': '用户组配置',
                'verbose_name_plural': '用户组配置',
                'ordering': ['sort_order', 'group__name'],
            },
        ),
    ]
