# Generated by Django 4.2.27 on 2026-05-04 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0005_auto_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, help_text='注册链接的唯一标识', max_length=64, unique=True, verbose_name='令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('used', models.BooleanField(default=False, help_text='此注册链接是否已被使用', verbose_name='已使用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('expires_at', models.DateTimeField(blank=True, help_text='留空表示永不过期', null=True, verbose_name='过期时间')),
                ('note', models.CharField(blank=True, help_text='管理员备注，仅后台可见', max_length=200, verbose_name='备注')),
                ('created_by', models.ForeignKey(help_text='创建此注册链接的管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_links', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('group', models.ForeignKey(help_text='通过此链接注册的用户将自动加入该用户组', on_delete=django.db.models.deletion.CASCADE, related_name='registration_links', to='auth.group', verbose_name='注册后用户组')),
                ('used_by', models.ForeignKey(blank=True, help_text='使用此链接注册的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_registration_link', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '注册链接',
                'verbose_name_plural': '注册链接',
                'ordering': ['-created_at'],
            },
        ),
    ]
