# Generated by Django 4.2.27 on 2026-02-01 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='CA名称')),
                ('private_key', models.TextField(verbose_name='私钥(加密存储)')),
                ('certificate', models.TextField(verbose_name='CA证书(PEM格式)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '证书颁发机构',
                'verbose_name_plural': '证书颁发机构',
                'db_table': 'certificate_authority',
            },
        ),
        migrations.CreateModel(
            name='ServerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='主机名')),
                ('private_key', models.TextField(verbose_name='私钥(加密存储)')),
                ('certificate', models.TextField(verbose_name='服务器证书(PEM格式)')),
                ('pfx_data', models.TextField(verbose_name='PFX数据(Base64编码)')),
                ('thumbprint', models.CharField(max_length=255, unique=True, verbose_name='证书指纹(SHA1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='是否已吊销')),
                ('revocation_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='吊销原因')),
                ('revocation_date', models.DateTimeField(blank=True, null=True, verbose_name='吊销时间')),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificateauthority', verbose_name='所属CA')),
            ],
            options={
                'verbose_name': '服务器证书',
                'verbose_name_plural': '服务器证书',
                'db_table': 'server_certificate',
            },
        ),
        migrations.CreateModel(
            name='ClientCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='证书名称')),
                ('private_key', models.TextField(verbose_name='私钥(加密存储)')),
                ('certificate', models.TextField(verbose_name='客户端证书(PEM格式)')),
                ('thumbprint', models.CharField(max_length=255, unique=True, verbose_name='证书指纹(SHA1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='分配给用户')),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificateauthority', verbose_name='所属CA')),
            ],
            options={
                'verbose_name': '客户端证书',
                'verbose_name_plural': '客户端证书',
                'db_table': 'client_certificate',
            },
        ),
    ]
