# Generated by Django 4.2.27 on 2026-02-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='clientcertificate',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='servercertificate',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
    ]
