# Generated by Django 4.2.27 on 2026-02-02 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0002_alter_certificateauthority_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateauthority',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='clientcertificate',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='servercertificate',
            name='private_key',
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='_private_key',
            field=models.TextField(db_column='private_key', default=1, verbose_name='私钥(加密)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcertificate',
            name='_private_key',
            field=models.TextField(db_column='private_key', default=1, verbose_name='私钥(加密)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servercertificate',
            name='_private_key',
            field=models.TextField(db_column='private_key', default=1, verbose_name='私钥(加密)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='certificate',
            field=models.TextField(verbose_name='CA证书(PEM)'),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientcertificate',
            name='assigned_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientcertificate',
            name='ca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificateauthority'),
        ),
        migrations.AlterField(
            model_name='clientcertificate',
            name='certificate',
            field=models.TextField(verbose_name='证书(PEM)'),
        ),
        migrations.AlterField(
            model_name='clientcertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientcertificate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcertificate',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcertificate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientcertificate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientcertificate',
            name='thumbprint',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='servercertificate',
            name='ca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificateauthority'),
        ),
        migrations.AlterField(
            model_name='servercertificate',
            name='certificate',
            field=models.TextField(verbose_name='证书(PEM)'),
        ),
        migrations.AlterField(
            model_name='servercertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servercertificate',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servercertificate',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servercertificate',
            name='pfx_data',
            field=models.TextField(verbose_name='PFX(Base64)'),
        ),
        migrations.AlterField(
            model_name='servercertificate',
            name='revocation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servercertificate',
            name='revocation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servercertificate',
            name='thumbprint',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
