# Generated by Django 4.2+ on migration creation

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(help_text='插件的唯一标识符', max_length=255, unique=True, verbose_name='插件ID')),
                ('name', models.CharField(help_text='插件的显示名称', max_length=255, verbose_name='插件名称')),
                ('version', models.CharField(default='1.0.0', help_text='插件的版本号', max_length=50, verbose_name='版本号')),
                ('description', models.TextField(blank=True, help_text='插件的功能描述', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, help_text='插件是否处于启用状态', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '插件',
                'verbose_name_plural': '插件',
                'db_table': 'plugin_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PluginConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='配置项的键名', max_length=255, verbose_name='配置键')),
                ('value', models.TextField(help_text='配置项的值', verbose_name='配置值')),
                ('description', models.TextField(blank=True, help_text='配置项的描述信息', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plugin', models.ForeignKey(on_delete=models.CASCADE, related_name='configurations', to='plugins.pluginrecord', verbose_name='关联插件')),
            ],
            options={
                'verbose_name': '插件配置',
                'verbose_name_plural': '插件配置',
                'db_table': 'plugin_configurations',
            },
        ),
        migrations.AddConstraint(
            model_name='pluginconfiguration',
            constraint=models.UniqueConstraint(fields=('plugin', 'key'), name='unique_plugin_key'),
        ),
    ]