# Generated by Django 4.2.27 on 2026-01-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQVerifyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='QQ机器人服务器的主机地址', max_length=255, verbose_name='机器人服务器地址')),
                ('port', models.CharField(help_text='QQ机器人服务器的端口', max_length=10, verbose_name='机器人服务器端口')),
                ('token', models.CharField(help_text='访问QQ机器人API的令牌', max_length=255, verbose_name='访问令牌')),
                ('group_id', models.CharField(help_text='需要验证的QQ群号', max_length=20, verbose_name='目标群号')),
                ('enable_status', models.CharField(choices=[('disabled', '禁用'), ('enabled_require_group', '启用-要求入群'), ('enabled_old_six_mode', '启用-老六模式'), ('enabled_both', '启用-两种模式')], default='disabled', help_text='QQ验证功能的启用状态和模式', max_length=25, verbose_name='启用状态')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='pluginconfiguration',
            name='unique_plugin_key',
        ),
        migrations.AlterUniqueTogether(
            name='pluginconfiguration',
            unique_together={('plugin', 'key')},
        ),
    ]
