# Generated by Django 4.2.27 on 2026-01-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_publichostinfo'),
        ('plugins', '0002_qqverifyconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQVerificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='QQ机器人服务器的主机地址', max_length=255, verbose_name='机器人服务器地址')),
                ('port', models.CharField(help_text='QQ机器人服务器的端口号', max_length=20, verbose_name='机器人服务器端口')),
                ('token', models.CharField(help_text='用于认证的访问令牌', max_length=255, verbose_name='访问令牌')),
                ('group_id', models.CharField(help_text='用于验证QQ号是否在群内的群号', max_length=20, verbose_name='验证群号')),
                ('enable_status', models.CharField(choices=[('disabled', '禁用'), ('enabled_require_group', '启用-要求入群'), ('enabled_old_six_mode', '启用-老六模式'), ('enabled_both', '启用-两种模式')], default='disabled', help_text='QQ验证功能的启用状态', max_length=25, verbose_name='启用状态')),
                ('non_qq_email_handling', models.CharField(choices=[('default_allow', '默认符合'), ('default_deny', '默认不符合'), ('manual_review', '等待人工处理')], default='default_deny', help_text='当用户使用非QQ邮箱时的处理策略', max_length=20, verbose_name='非QQ邮箱处理策略')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.OneToOneField(help_text='此QQ验证配置关联的产品', on_delete=django.db.models.deletion.CASCADE, related_name='qq_verification_config', to='operations.product', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': 'QQ验证配置',
                'verbose_name_plural': 'QQ验证配置',
                'unique_together': {('product',)},
            },
        ),
    ]