# Generated by Django 4.2.27 on 2026-02-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0005_auto_20260130_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QQVerifyConfig',
        ),
        migrations.AlterModelOptions(
            name='pluginrecord',
            options={'ordering': ['-created_at'], 'verbose_name': '插件记录', 'verbose_name_plural': '插件记录'},
        ),
        migrations.AlterField(
            model_name='pluginconfiguration',
            name='description',
            field=models.TextField(blank=True, help_text='配置项的描述', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='pluginconfiguration',
            name='key',
            field=models.CharField(help_text='配置参数的键名', max_length=200, verbose_name='配置键'),
        ),
        migrations.AlterField(
            model_name='pluginconfiguration',
            name='plugin',
            field=models.ForeignKey(help_text='配置所属的插件', on_delete=django.db.models.deletion.CASCADE, to='plugins.pluginrecord', verbose_name='插件'),
        ),
        migrations.AlterField(
            model_name='pluginconfiguration',
            name='value',
            field=models.TextField(help_text='配置参数的值', verbose_name='配置值'),
        ),
        migrations.AlterField(
            model_name='pluginrecord',
            name='description',
            field=models.TextField(blank=True, help_text='插件的详细描述', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='pluginrecord',
            name='is_active',
            field=models.BooleanField(default=True, help_text='插件是否处于激活状态', verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='pluginrecord',
            name='name',
            field=models.CharField(help_text='插件的显示名称', max_length=200, verbose_name='插件名称'),
        ),
        migrations.AlterField(
            model_name='pluginrecord',
            name='plugin_id',
            field=models.CharField(help_text='插件的唯一标识符', max_length=100, unique=True, verbose_name='插件ID'),
        ),
        migrations.AlterField(
            model_name='pluginrecord',
            name='version',
            field=models.CharField(help_text='插件的版本号', max_length=50, verbose_name='版本号'),
        ),
        migrations.AddConstraint(
            model_name='pluginconfiguration',
            constraint=models.UniqueConstraint(fields=('plugin', 'key'), name='unique_plugin_key'),
        ),
        migrations.AlterModelTable(
            name='pluginconfiguration',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pluginrecord',
            table=None,
        ),
    ]
