# Generated by Django 4.2.27 on 2026-05-02 09:15

from django.db import migrations, models


def migrate_group_id_to_group_ids(apps, schema_editor):
    QQVerificationConfig = apps.get_model(
        'plugins', 'QQVerificationConfig'
    )
    for config in QQVerificationConfig.objects.all():
        old_group_id = getattr(config, 'group_id', None)
        if old_group_id:
            config.group_ids = old_group_id
            config.save(update_fields=['group_ids'])


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0006_delete_qqverifyconfig_alter_pluginrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qqverificationconfig',
            name='group_ids',
            field=models.TextField(blank=True, help_text='用于验证QQ号是否在群内的群号，每行一个QQ群号', null=True, verbose_name='验证群号'),
        ),
        migrations.AddField(
            model_name='qqverificationconfig',
            name='use_default_bot',
            field=models.BooleanField(default=True, help_text='启用后使用系统配置中的默认机器人服务器地址、端口和令牌', verbose_name='使用系统默认机器人服务器'),
        ),
        migrations.AlterField(
            model_name='qqverificationconfig',
            name='host',
            field=models.CharField(blank=True, help_text='QQ机器人服务器的主机地址', max_length=255, null=True, verbose_name='机器人服务器地址'),
        ),
        migrations.AlterField(
            model_name='qqverificationconfig',
            name='port',
            field=models.CharField(blank=True, help_text='QQ机器人服务器的端口号', max_length=20, null=True, verbose_name='机器人服务器端口'),
        ),
        migrations.AlterField(
            model_name='qqverificationconfig',
            name='token',
            field=models.CharField(blank=True, help_text='用于认证的访问令牌', max_length=255, null=True, verbose_name='访问令牌'),
        ),
        migrations.RunPython(
            migrate_group_id_to_group_ids,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='qqverificationconfig',
            name='group_id',
        ),
    ]
