# Generated by Django 4.2.27 on 2026-01-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_alter_host_password_rename_password_host__password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(default=5985, verbose_name='WinRM端口'),
        ),
        migrations.DeleteModel(
            name='HostPermission',
        ),
    ]
