# Generated by Django 4.2.27 on 2026-02-02 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_host_connection_type_alter_host_port'),
        ('bootstrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstraptoken',
            name='is_paired',
            field=models.BooleanField(default=False, verbose_name='是否已配对'),
        ),
        migrations.AddField(
            model_name='bootstraptoken',
            name='paired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='配对时间'),
        ),
        migrations.AddField(
            model_name='bootstraptoken',
            name='pairing_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='配对码'),
        ),
        migrations.AddField(
            model_name='bootstraptoken',
            name='pairing_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='配对码过期时间'),
        ),
        migrations.AlterField(
            model_name='bootstraptoken',
            name='host',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.host', verbose_name='关联主机'),
        ),
    ]
