# Generated by Django 4.2.27 on 2026-02-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0002_bootstraptoken_is_paired_bootstraptoken_paired_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstraptoken',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='TOTP密钥'),
        ),
    ]
