# Generated by Django 4.2.27 on 2026-02-02 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_host_connection_type_alter_host_port'),
        ('bootstrap', '0003_bootstraptoken_totp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootstraptoken',
            name='pairing_code',
        ),
        migrations.RemoveField(
            model_name='bootstraptoken',
            name='pairing_code_expires_at',
        ),
        migrations.AlterField(
            model_name='bootstraptoken',
            name='host',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hosts.host', verbose_name='关联主机'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InitialToken',
            fields=[
                ('token', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='AccessToken')),
                ('expires_at', models.DateTimeField(verbose_name='AccessToken过期时间')),
                ('status', models.CharField(choices=[('ISSUED', '已签发'), ('TOTP_VERIFIED', '已验证'), ('CONSUMED', '已消耗')], default='ISSUED', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host', verbose_name='关联的主机')),
            ],
            options={
                'verbose_name': '初始令牌',
                'verbose_name_plural': '初始令牌',
                'db_table': 'initial_token',
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('session_token', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='临时凭证')),
                ('bound_ip', models.GenericIPAddressField(verbose_name='绑定的请求源IP')),
                ('expires_at', models.DateTimeField(verbose_name='24小时后的过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host', verbose_name='关联的主机')),
            ],
            options={
                'verbose_name': '活动会话',
                'verbose_name_plural': '活动会话',
                'db_table': 'active_session',
            },
        ),
    ]
