# Generated by Django 4.2.27 on 2026-02-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0004_remove_bootstraptoken_pairing_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BootstrapToken',
        ),
    ]
