# Generated by Django 4.2.27 on 2026-02-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0005_delete_bootstraptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='expires_at',
            field=models.DateTimeField(verbose_name='会话过期时间'),
        ),
    ]
