# Generated by Django 4.2.27 on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0006_alter_activesession_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialtoken',
            name='pairing_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='配对码'),
        ),
        migrations.AddField(
            model_name='initialtoken',
            name='pairing_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='配对码过期时间'),
        ),
        migrations.AlterField(
            model_name='initialtoken',
            name='status',
            field=models.CharField(choices=[('ISSUED', '已签发'), ('PAIRED', '已配对'), ('CONSUMED', '已消耗')], default='ISSUED', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='expires_at',
            field=models.DateTimeField(verbose_name='会话过期时间'),
        ),
    ]