# Generated by Django 4.2.27 on 2026-05-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0007_update_initialtoken_for_pairing'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialtoken',
            name='pairing_attempts',
            field=models.IntegerField(default=0, verbose_name='配对码验证尝试次数'),
        ),
    ]
