from django.urls import path

from .views_provider import (
    TicketActivityListView,
    TicketAttachmentDownloadView,
    TicketAttachmentUploadView,
    TicketBatchClosedView,
    TicketBatchProcessingView,
    TicketBatchResolvedView,
    TicketCategoryCreateView,
    TicketCategoryDeleteView,
    TicketCategoryListView,
    TicketCategoryUpdateView,
    TicketCommentCreateView,
    TicketDetailView,
    TicketListView,
)

app_name = 'provider_tickets'

urlpatterns = [
    path(
        'categories/',
        TicketCategoryListView.as_view(),
        name='category_list',
    ),
    path(
        'categories/create/',
        TicketCategoryCreateView.as_view(),
        name='category_create',
    ),
    path(
        'categories/<int:pk>/edit/',
        TicketCategoryUpdateView.as_view(),
        name='category_edit',
    ),
    path(
        'categories/<int:pk>/delete/',
        TicketCategoryDeleteView.as_view(),
        name='category_delete',
    ),
    path(
        '',
        TicketListView.as_view(),
        name='ticket_list',
    ),
    path(
        '<int:pk>/',
        TicketDetailView.as_view(),
        name='ticket_detail',
    ),
    path(
        'batch-processing/',
        TicketBatchProcessingView.as_view(),
        name='ticket_batch_processing',
    ),
    path(
        'batch-resolved/',
        TicketBatchResolvedView.as_view(),
        name='ticket_batch_resolved',
    ),
    path(
        'batch-closed/',
        TicketBatchClosedView.as_view(),
        name='ticket_batch_closed',
    ),
    path(
        '<int:pk>/comment/',
        TicketCommentCreateView.as_view(),
        name='ticket_comment_create',
    ),
    path(
        'activities/',
        TicketActivityListView.as_view(),
        name='activity_list',
    ),
    path(
        '<int:ticket_pk>/attachments/upload/',
        TicketAttachmentUploadView.as_view(),
        name='attachment_upload',
    ),
    path(
        'attachments/<int:pk>/download/',
        TicketAttachmentDownloadView.as_view(),
        name='attachment_download',
    ),
]
