# Generated by Django 4.2.27 on 2026-04-26 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0011_rename_operations_rdp_domain_idx_operations__domain_5c01f5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosts', '0010_remove_host_host_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(help_text='自动生成的唯一工单编号', max_length=20, unique=True, verbose_name='工单编号')),
                ('title', models.CharField(help_text='工单的简要标题', max_length=200, verbose_name='标题')),
                ('description', models.TextField(help_text='工单的详细描述', verbose_name='详细描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('waiting_feedback', '待反馈'), ('resolved', '已解决'), ('closed', '已关闭'), ('rejected', '已驳回')], default='pending', help_text='工单的当前状态', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', help_text='工单的优先级', max_length=20, verbose_name='优先级')),
                ('source', models.CharField(choices=[('web', 'Web提交'), ('api', 'API创建'), ('system', '系统自动生成'), ('email', '邮件导入')], default='web', help_text='工单的创建来源', max_length=20, verbose_name='来源')),
                ('due_at', models.DateTimeField(blank=True, help_text='根据SLA计算的工单处理截止时间', null=True, verbose_name='截止时间')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='工单被标记为已解决的时间', null=True, verbose_name='解决时间')),
                ('closed_at', models.DateTimeField(blank=True, help_text='工单被关闭的时间', null=True, verbose_name='关闭时间')),
                ('satisfaction', models.PositiveSmallIntegerField(blank=True, help_text='用户对工单处理的满意度评分（1-5）', null=True, verbose_name='满意度评分')),
                ('satisfaction_comment', models.TextField(blank=True, help_text='用户对工单处理的评价内容', verbose_name='满意度评价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, help_text='负责处理此工单的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='工单分类的名称', max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, help_text='分类的详细描述', verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, default='help_outline', help_text='Material Icons 图标名称', max_length=50, verbose_name='图标')),
                ('default_priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', help_text='该分类下工单的默认优先级', max_length=20, verbose_name='默认优先级')),
                ('sla_hours', models.PositiveIntegerField(default=24, help_text='工单处理的服务级别协议时限', verbose_name='SLA时限(小时)')),
                ('is_active', models.BooleanField(default=True, help_text='是否在前端展示此分类', verbose_name='是否启用')),
                ('display_order', models.IntegerField(default=0, help_text='分类在前端展示的顺序，数字越小越靠前', verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('auto_assign_to', models.ForeignKey(blank=True, help_text='该分类的工单自动分配给指定用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_assigned_categories', to=settings.AUTH_USER_MODEL, verbose_name='自动分配给')),
            ],
            options={
                'verbose_name': '工单分类',
                'verbose_name_plural': '工单分类',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='上传的附件文件', upload_to='ticket_attachments/%Y/%m/', verbose_name='文件')),
                ('filename', models.CharField(help_text='文件的原始名称', max_length=255, verbose_name='原始文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ticket', models.ForeignKey(help_text='附件所属的工单', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='关联工单')),
                ('uploaded_by', models.ForeignKey(help_text='上传此附件的用户', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '工单附件',
                'verbose_name_plural': '工单附件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('assign', '分配'), ('status_change', '状态变更'), ('comment', '评论'), ('close', '关闭'), ('update', '更新')], help_text='活动的操作类型', max_length=20, verbose_name='操作类型')),
                ('old_value', models.CharField(blank=True, help_text='变更前的值', max_length=255, verbose_name='旧值')),
                ('new_value', models.CharField(blank=True, help_text='变更后的值', max_length=255, verbose_name='新值')),
                ('description', models.TextField(blank=True, help_text='活动的详细描述', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(blank=True, help_text='执行此操作的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('ticket', models.ForeignKey(help_text='活动所属的工单', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tickets.ticket', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '工单活动',
                'verbose_name_plural': '工单活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, help_text='工单所属的分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketcategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(help_text='提交工单的用户', on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_host',
            field=models.ForeignKey(blank=True, help_text='工单关联的主机', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='hosts.host', verbose_name='关联主机'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_product',
            field=models.ForeignKey(blank=True, help_text='工单关联的云电脑产品', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='operations.product', verbose_name='关联产品'),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='评论的详细内容', verbose_name='内容')),
                ('is_internal', models.BooleanField(default=False, help_text='是否为仅工作人员可见的内部备注', verbose_name='内部备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(help_text='评论的作者', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('ticket', models.ForeignKey(help_text='评论所属的工单', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '工单评论',
                'verbose_name_plural': '工单评论',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='tickets_tic_ticket__254c10_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ticketcategory',
            index=models.Index(fields=['is_active'], name='tickets_tic_is_acti_d49b55_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategory',
            index=models.Index(fields=['display_order'], name='tickets_tic_display_3ed776_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketactivity',
            index=models.Index(fields=['ticket', 'created_at'], name='tickets_tic_ticket__de2dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_no'], name='tickets_tic_ticket__c7390a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='tickets_tic_priorit_0bec9b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assignee'], name='tickets_tic_assigne_8f75bf_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['creator'], name='tickets_tic_creator_3210bf_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['category'], name='tickets_tic_categor_3266ff_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['due_at'], name='tickets_tic_due_at_b8e2ab_idx'),
        ),
    ]
