# Generated by Django 4.2.27 on 2026-04-30 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='创建此分类的用户，用于提供商数据隔离', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ticket_categories', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
