# Generated by Django 4.2.27 on 2026-05-02 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0002_add_created_by_to_ticketcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_group',
            field=models.ForeignKey(blank=True, help_text='负责处理此工单的用户组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='auth.group', verbose_name='处理组'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='auto_assign_to_group',
            field=models.ForeignKey(blank=True, help_text='该分类的工单自动分配给指定用户组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_assigned_categories', to='auth.group', verbose_name='自动分配给用户组'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_group'], name='tickets_tic_assigne_161ff4_idx'),
        ),
    ]
