# Generated by Django 4.2.27 on 2026-02-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_theme', models.CharField(choices=[('material-design-3', 'Material Design 3'), ('neumorphism', '新拟态')], db_index=True, default='material-design-3', max_length=50, verbose_name='当前主题')),
                ('branding', models.JSONField(blank=True, default=dict, help_text='存储品牌资源路径：logo, logo_dark, favicon, login_bg', verbose_name='品牌资源')),
                ('custom_colors', models.JSONField(blank=True, default=dict, help_text='自定义 CSS 颜色变量', verbose_name='自定义颜色')),
                ('css_overrides', models.TextField(blank=True, help_text='自定义 CSS 样式覆盖', verbose_name='自定义 CSS')),
                ('enable_mobile_optimization', models.BooleanField(default=True, verbose_name='启用移动端优化')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '主题配置',
                'verbose_name_plural': '主题配置',
            },
        ),
        migrations.CreateModel(
            name='WidgetLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='组件类型')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='显示顺序')),
                ('column_span', models.PositiveSmallIntegerField(choices=[(1, '1列'), (2, '2列'), (3, '3列'), (4, '全宽')], default=1, help_text='在12列栅格中占据的列数比例', verbose_name='列跨度')),
                ('row_span', models.PositiveSmallIntegerField(choices=[(1, '1行'), (2, '2行')], default=1, verbose_name='行跨度')),
                ('is_visible', models.BooleanField(db_index=True, default=True, verbose_name='是否显示')),
                ('responsive', models.JSONField(blank=True, default=dict, help_text='各设备的显示配置', verbose_name='响应式配置')),
            ],
            options={
                'verbose_name': '组件布局',
                'verbose_name_plural': '组件布局',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['display_order', 'is_visible'], name='themes_widg_display_b4e1ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('login_welcome', '登录页欢迎语'), ('login_subtitle', '登录页副标题'), ('dashboard_notice', '仪表盘公告'), ('footer_text', '页脚文字'), ('footer_copyright', '版权信息'), ('maintenance_message', '维护提示'), ('register_terms', '注册条款')], db_index=True, max_length=50, unique=True, verbose_name='位置标识')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, help_text='支持 HTML 格式', verbose_name='内容')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='存储额外配置：icon, color, link 等', verbose_name='元数据')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '页面内容',
                'verbose_name_plural': '页面内容',
                'indexes': [models.Index(fields=['position', 'is_enabled'], name='themes_page_positio_508e18_idx')],
            },
        ),
    ]
