# Generated by Django 4.2.27 on 2026-01-26 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOpeningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(help_text='申请人联系方式', max_length=254, verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(blank=True, help_text='申请人联系电话', max_length=20, null=True, verbose_name='联系电话')),
                ('username', models.CharField(help_text='希望在云电脑上创建的用户名', max_length=150, verbose_name='用户名')),
                ('user_fullname', models.CharField(help_text='用户真实姓名', max_length=200, verbose_name='用户姓名')),
                ('user_email', models.EmailField(help_text='用户邮箱地址', max_length=254, verbose_name='用户邮箱')),
                ('user_description', models.TextField(blank=True, help_text='关于该用户的附加信息', verbose_name='用户描述')),
                ('requested_password', models.CharField(blank=True, help_text='用户希望设置的初始密码，留空则系统生成', max_length=128, null=True, verbose_name='用户指定密码')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', help_text='开户申请的当前状态', max_length=20, verbose_name='申请状态')),
                ('approval_date', models.DateTimeField(blank=True, help_text='申请被审核的时间', null=True, verbose_name='审核时间')),
                ('approval_notes', models.TextField(blank=True, help_text='审核时的备注信息', verbose_name='审核备注')),
                ('cloud_user_id', models.CharField(blank=True, help_text='在云电脑上实际创建的用户ID', max_length=255, verbose_name='云电脑用户ID')),
                ('cloud_user_password', models.CharField(blank=True, help_text='为用户设置的初始密码', max_length=255, verbose_name='云电脑用户密码')),
                ('result_message', models.TextField(blank=True, help_text='开户操作的结果信息', verbose_name='结果信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='申请创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='申请信息最后更新时间', verbose_name='更新时间')),
                ('applicant', models.ForeignKey(help_text='提交开户申请的用户', on_delete=django.db.models.deletion.CASCADE, related_name='account_opening_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approved_by', models.ForeignKey(blank=True, help_text='批准此申请的管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_account_requests', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '开户申请',
                'verbose_name_plural': '开户申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='面向用户展示的产品名称', max_length=200, verbose_name='产品名称')),
                ('description', models.TextField(blank=True, help_text='产品的详细描述，支持Markdown格式', verbose_name='产品描述')),
                ('display_name', models.CharField(help_text='在前端展示的产品名称', max_length=200, verbose_name='显示名称')),
                ('display_description', models.TextField(blank=True, help_text='在前端展示的产品描述，支持Markdown格式', verbose_name='显示描述')),
                ('rdp_port', models.IntegerField(default=3389, help_text='用户连接时使用的RDP端口', verbose_name='RDP端口')),
                ('display_hostname', models.CharField(help_text='在前端展示的产品访问地址', max_length=255, verbose_name='显示地址')),
                ('is_available', models.BooleanField(default=True, help_text='是否在前端展示此产品', verbose_name='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host', models.ForeignKey(help_text='此产品运行所在的主机', on_delete=django.db.models.deletion.CASCADE, to='hosts.host', verbose_name='关联主机')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='CloudComputerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='在云电脑上的用户名', max_length=150, verbose_name='用户名')),
                ('fullname', models.CharField(help_text='用户真实姓名', max_length=200, verbose_name='用户姓名')),
                ('email', models.EmailField(help_text='用户邮箱地址', max_length=254, verbose_name='用户邮箱')),
                ('description', models.TextField(blank=True, help_text='关于该用户的附加信息', verbose_name='用户描述')),
                ('status', models.CharField(choices=[('active', '激活'), ('inactive', '未激活'), ('disabled', '已禁用'), ('deleted', '已删除')], default='active', help_text='用户在云电脑上的状态', max_length=20, verbose_name='用户状态')),
                ('is_admin', models.BooleanField(default=False, help_text='是否具有管理员权限', verbose_name='管理员权限')),
                ('groups', models.TextField(blank=True, help_text='用户所属的组（逗号分隔）', verbose_name='用户组')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='用户在云电脑上创建的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='信息最后更新时间', verbose_name='更新时间')),
                ('created_from_request', models.ForeignKey(blank=True, help_text='创建此用户的开户申请', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.accountopeningrequest', verbose_name='来源申请')),
                ('product', models.ForeignKey(help_text='该用户所属的云电脑产品', on_delete=django.db.models.deletion.CASCADE, to='operations.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '云电脑用户',
                'verbose_name_plural': '云电脑用户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='accountopeningrequest',
            name='target_product',
            field=models.ForeignKey(blank=True, help_text='要在哪个产品上创建用户', null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.product', verbose_name='目标产品'),
        ),
        migrations.CreateModel(
            name='SystemTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='任务的名称', max_length=200, verbose_name='任务名称')),
                ('task_type', models.CharField(help_text='任务的类型，如batch_create_user等', max_length=100, verbose_name='任务类型')),
                ('description', models.TextField(blank=True, help_text='任务的详细描述', null=True, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', help_text='任务的执行状态', max_length=20, verbose_name='任务状态')),
                ('progress', models.IntegerField(default=0, help_text='任务执行进度，0-100', verbose_name='执行进度')),
                ('result', models.TextField(blank=True, help_text='任务执行的结果信息', null=True, verbose_name='执行结果')),
                ('error_message', models.TextField(blank=True, help_text='任务执行失败时的错误信息', null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='任务创建时间', verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, help_text='任务开始执行的时间', null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, help_text='任务完成的时间', null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建该任务的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '系统任务',
                'verbose_name_plural': '系统任务',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='operations__status_4c55d9_idx'), models.Index(fields=['task_type'], name='operations__task_ty_240239_idx'), models.Index(fields=['created_at'], name='operations__created_b8e18a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='operations__is_avai_fe927c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['host'], name='operations__host_id_e9faab_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='operations__created_8529c5_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudcomputeruser',
            index=models.Index(fields=['product'], name='operations__product_684d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudcomputeruser',
            index=models.Index(fields=['username'], name='operations__usernam_fe9d86_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudcomputeruser',
            index=models.Index(fields=['status'], name='operations__status_27a9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudcomputeruser',
            index=models.Index(fields=['created_at'], name='operations__created_98027d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cloudcomputeruser',
            unique_together={('product', 'username')},
        ),
        migrations.AddIndex(
            model_name='accountopeningrequest',
            index=models.Index(fields=['applicant'], name='operations__applica_1b5fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='accountopeningrequest',
            index=models.Index(fields=['status'], name='operations__status_c941d7_idx'),
        ),
        migrations.AddIndex(
            model_name='accountopeningrequest',
            index=models.Index(fields=['target_product'], name='operations__target__a69322_idx'),
        ),
        migrations.AddIndex(
            model_name='accountopeningrequest',
            index=models.Index(fields=['created_at'], name='operations__created_9035ca_idx'),
        ),
    ]
