# Generated by Django 4.2.27 on 2026-01-26 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_alter_hostgroup_hosts'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHostInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='在前端展示的主机名称', max_length=200, verbose_name='显示名称')),
                ('display_description', models.TextField(blank=True, help_text='在前端展示的主机描述，支持Markdown格式', verbose_name='显示描述')),
                ('display_hostname', models.CharField(help_text='在前端展示的主机地址', max_length=255, verbose_name='显示地址')),
                ('display_rdp_port', models.IntegerField(default=3389, help_text='在前端展示的RDP端口', verbose_name='显示RDP端口')),
                ('is_available', models.BooleanField(default=True, help_text='是否在前端展示此主机', verbose_name='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('internal_host', models.OneToOneField(help_text='关联的内部主机', on_delete=django.db.models.deletion.CASCADE, to='hosts.host', verbose_name='内部主机')),
            ],
            options={
                'verbose_name': '公开主机信息',
                'verbose_name_plural': '公开主机信息',
                'indexes': [models.Index(fields=['is_available'], name='operations__is_avai_9e6881_idx'), models.Index(fields=['internal_host'], name='operations__interna_acf3ff_idx')],
            },
        ),
    ]
