# Generated by Django 4.2.27 on 2026-02-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_manual_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountopeningrequest',
            name='requested_password',
        ),
        migrations.AddField(
            model_name='cloudcomputeruser',
            name='initial_password',
            field=models.CharField(blank=True, help_text='用户的初始密码，查看后将被清除', max_length=255, verbose_name='初始密码'),
        ),
        migrations.AddField(
            model_name='cloudcomputeruser',
            name='password_viewed',
            field=models.BooleanField(default=False, help_text='指示初始密码是否已被查看', verbose_name='密码已查看'),
        ),
        migrations.AddField(
            model_name='cloudcomputeruser',
            name='password_viewed_at',
            field=models.DateTimeField(blank=True, help_text='初始密码被查看的时间', null=True, verbose_name='密码查看时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='auto_approval',
            field=models.BooleanField(default=False, help_text='是否自动批准针对此产品的开户申请', verbose_name='自动审核'),
        ),
    ]
