# Generated by Django 4.2.27 on 2026-02-02 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0004_remove_accountopeningrequest_requested_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudcomputeruser',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='拥有此云电脑账户的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_users', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
    ]
