# Generated by Django 4.2.27 on 2026-04-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_product_enable_host_protection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rdpdomainroute',
            new_name='operations__domain_5c01f5_idx',
            old_name='operations_rdp_domain_idx',
        ),
        migrations.RenameIndex(
            model_name='rdpdomainroute',
            new_name='operations__is_acti_ba9cb3_idx',
            old_name='operations_rdp_active_idx',
        ),
        migrations.RenameIndex(
            model_name='rdpdomainroute',
            new_name='operations__assigne_ecc986_idx',
            old_name='operations_rdp_user_idx',
        ),
        migrations.RenameIndex(
            model_name='rdpdomainroute',
            new_name='operations__expires_8306ea_idx',
            old_name='operations_rdp_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='rdpdomainroute',
            new_name='operations__product_ccd619_idx',
            old_name='operations_rdp_product_idx',
        ),
    ]
