# Generated by Django 4.2.27 on 2026-04-29 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0011_rename_operations_rdp_domain_idx_operations__domain_5c01f5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('invite_only', '邀请访问')], default='public', help_text='产品的可见性：公开对所有用户可见，邀请访问仅对已授权用户可见', max_length=20, verbose_name='可见性'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('invite_only', '邀请访问')], default='public', help_text='产品组的可见性：公开对所有用户可见，邀请访问仅对已授权用户可见', max_length=20, verbose_name='可见性'),
        ),
        migrations.CreateModel(
            name='ProductInvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='用于邀请链接的唯一令牌', max_length=64, unique=True, verbose_name='邀请令牌')),
                ('max_uses', models.IntegerField(default=0, help_text='令牌最大可使用次数，0表示无限制', verbose_name='最大使用次数')),
                ('used_count', models.IntegerField(default=0, help_text='令牌已被使用的次数', verbose_name='已使用次数')),
                ('expires_at', models.DateTimeField(blank=True, help_text='令牌过期时间，留空表示永不过期', null=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, help_text='令牌是否有效', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(help_text='创建此邀请令牌的用户', on_delete=django.db.models.deletion.CASCADE, related_name='created_invitation_tokens', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('product', models.ForeignKey(blank=True, help_text='此令牌关联的产品（与产品组至少选一个）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_tokens', to='operations.product', verbose_name='关联产品')),
                ('product_group', models.ForeignKey(blank=True, help_text='此令牌关联的产品组（与产品至少选一个）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_tokens', to='operations.productgroup', verbose_name='关联产品组')),
            ],
            options={
                'verbose_name': '产品邀请令牌',
                'verbose_name_plural': '产品邀请令牌',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('expires_at', models.DateTimeField(blank=True, help_text='访问权限过期时间，留空表示永久有效', null=True, verbose_name='授权过期时间')),
                ('is_revoked', models.BooleanField(default=False, help_text='权限是否已被撤销', verbose_name='是否已撤销')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('granted_by_token', models.ForeignKey(blank=True, help_text='通过哪个邀请令牌获得的权限', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grants', to='operations.productinvitationtoken', verbose_name='来源邀请令牌')),
                ('product', models.ForeignKey(blank=True, help_text='授权访问的产品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='operations.product', verbose_name='关联产品')),
                ('product_group', models.ForeignKey(blank=True, help_text='授权访问的产品组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='operations.productgroup', verbose_name='关联产品组')),
                ('revoked_by', models.ForeignKey(blank=True, help_text='撤销此权限的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_access_grants', to=settings.AUTH_USER_MODEL, verbose_name='撤销人')),
                ('user', models.ForeignKey(help_text='获得访问权限的用户', on_delete=django.db.models.deletion.CASCADE, related_name='product_access_grants', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '产品访问授权',
                'verbose_name_plural': '产品访问授权',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productinvitationtoken',
            index=models.Index(fields=['token'], name='operations__token_43deaf_idx'),
        ),
        migrations.AddIndex(
            model_name='productinvitationtoken',
            index=models.Index(fields=['is_active'], name='operations__is_acti_8900c8_idx'),
        ),
        migrations.AddIndex(
            model_name='productinvitationtoken',
            index=models.Index(fields=['expires_at'], name='operations__expires_b456ac_idx'),
        ),
        migrations.AddIndex(
            model_name='productinvitationtoken',
            index=models.Index(fields=['created_by'], name='operations__created_a0e391_idx'),
        ),
        migrations.AddIndex(
            model_name='productaccessgrant',
            index=models.Index(fields=['user'], name='operations__user_id_2e640b_idx'),
        ),
        migrations.AddIndex(
            model_name='productaccessgrant',
            index=models.Index(fields=['product'], name='operations__product_f577f6_idx'),
        ),
        migrations.AddIndex(
            model_name='productaccessgrant',
            index=models.Index(fields=['product_group'], name='operations__product_691717_idx'),
        ),
        migrations.AddIndex(
            model_name='productaccessgrant',
            index=models.Index(fields=['is_revoked'], name='operations__is_revo_0fe57f_idx'),
        ),
        migrations.AddIndex(
            model_name='productaccessgrant',
            index=models.Index(fields=['granted_at'], name='operations__granted_d3fe5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='productaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('user', 'product'), name='unique_user_product_grant'),
        ),
        migrations.AddConstraint(
            model_name='productaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('product_group__isnull', False)), fields=('user', 'product_group'), name='unique_user_productgroup_grant'),
        ),
    ]
