# Generated by Django 4.2.27 on 2026-04-29 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0012_product_visibility_productgroup_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='创建此产品组的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
