# Generated by Django 4.2.27 on 2026-02-01 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hosts', '0005_host_connection_type_alter_host_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='会话密钥')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='登出时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会话活动',
                'verbose_name_plural': '会话活动',
                'db_table': 'session_activity',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=50, verbose_name='操作类型')),
                ('target', models.CharField(max_length=255, verbose_name='操作目标')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('ip_address', models.GenericIPAddressField(verbose_name='操作IP')),
                ('justification', models.TextField(verbose_name='操作理由')),
                ('approved_at', models.DateTimeField(null=True, verbose_name='批准时间')),
                ('result', models.TextField(blank=True, null=True, verbose_name='操作结果')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sensitive_ops', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '敏感操作',
                'verbose_name_plural': '敏感操作',
                'db_table': 'sensitive_operation',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('unauthorized_access', '未授权访问'), ('failed_login', '登录失败'), ('suspicious_activity', '可疑活动'), ('data_exposure', '数据暴露风险'), ('privilege_escalation', '权限提升尝试'), ('cert_compromise', '证书泄露'), ('brute_force', '暴力破解')], max_length=50, verbose_name='事件类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=10, verbose_name='严重程度')),
                ('ip_address', models.GenericIPAddressField(verbose_name='事件IP')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('resolved', models.BooleanField(default=False, verbose_name='已解决')),
                ('resolved_at', models.DateTimeField(null=True, verbose_name='解决时间')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='解决备注')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL, verbose_name='解决人')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '安全事件',
                'verbose_name_plural': '安全事件',
                'db_table': 'security_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_user', '创建用户'), ('delete_user', '删除用户'), ('reset_password', '重置密码'), ('connect_host', '连接主机'), ('modify_host', '修改主机'), ('view_password', '查看密码'), ('approve_request', '审批请求'), ('reject_request', '拒绝请求'), ('bootstrap_host', '初始化主机'), ('issue_cert', '签发证书'), ('revoke_cert', '吊销证书'), ('create_host', '创建主机'), ('delete_host', '删除主机'), ('update_host', '更新主机'), ('process_opening_request', '处理开户请求'), ('batch_process_requests', '批量处理请求'), ('login', '用户登录'), ('logout', '用户登出'), ('view_audit_log', '查看审计日志'), ('admin_action', '管理员操作')], max_length=50, verbose_name='操作类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作IP地址')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('success', models.BooleanField(default=True, verbose_name='操作成功')),
                ('details', models.JSONField(default=dict, verbose_name='操作详情')),
                ('result', models.TextField(blank=True, null=True, verbose_name='操作结果')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='关联对象类型')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosts.host', verbose_name='操作主机')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_log_user_id_835db7_idx'), models.Index(fields=['host', 'timestamp'], name='audit_log_host_id_51b348_idx'), models.Index(fields=['action', 'timestamp'], name='audit_log_action_09d227_idx'), models.Index(fields=['timestamp'], name='audit_log_timesta_e8e14e_idx')],
            },
        ),
    ]
