# Generated by Django 4.2.27 on 2026-01-26 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='主机名称')),
                ('hostname', models.CharField(max_length=255, verbose_name='主机地址')),
                ('port', models.IntegerField(default=5985, verbose_name='WinRM端口')),
                ('rdp_port', models.IntegerField(default=3389, verbose_name='RDP端口')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='使用SSL')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('host_type', models.CharField(choices=[('server', '服务器'), ('workstation', '工作站'), ('laptop', '笔记本'), ('desktop', '台式机')], max_length=20, verbose_name='主机类型')),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='操作系统版本')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('error', '错误')], default='offline', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'db_table': 'hosts_host',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='组名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hosts', models.ManyToManyField(blank=True, to='hosts.host', verbose_name='包含主机')),
            ],
            options={
                'verbose_name': '主机组',
                'verbose_name_plural': '主机组',
                'db_table': 'hosts_hostgroup',
            },
        ),
    ]
