# Generated by Django 4.2.27 on 2026-01-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgroup',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='hosts.host', verbose_name='主机'),
        ),
    ]
