# Generated by Django 4.2.27 on 2026-01-26 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosts', '0002_alter_hostgroup_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='password',
            field=models.CharField(db_column='password', max_length=255, verbose_name='密码'),
        ),
        migrations.RenameField(
            model_name='host',
            old_name='password',
            new_name='_password',
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(default=5985, verbose_name='WinRM端Port'),
        ),
        migrations.CreateModel(
            name='HostPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False, help_text='是否可以编辑主机信息', verbose_name='编辑权限')),
                ('can_manage_products', models.BooleanField(default=False, help_text='是否可以在该主机上管理产品', verbose_name='产品上架权限')),
                ('can_review_requests', models.BooleanField(default=False, help_text='是否可以审核该主机相关的开户申请', verbose_name='审核权限')),
                ('can_manage_cloud_users', models.BooleanField(default=False, help_text='是否可以管理该主机上的云电脑用户', verbose_name='云电脑用户管理权限')),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='权限授予的时间', verbose_name='授权时间')),
                ('expires_at', models.DateTimeField(blank=True, help_text='权限过期时间，留空表示永久有效', null=True, verbose_name='过期时间')),
                ('granted_by', models.ForeignKey(blank=True, help_text='授予此权限的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='授权人')),
                ('host', models.ForeignKey(help_text='被授权的主机', on_delete=django.db.models.deletion.CASCADE, to='hosts.host', verbose_name='主机')),
                ('user', models.ForeignKey(help_text='拥有权限的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '主机权限',
                'verbose_name_plural': '主机权限',
                'indexes': [models.Index(fields=['user'], name='hosts_hostp_user_id_580592_idx'), models.Index(fields=['host'], name='hosts_hostp_host_id_085956_idx'), models.Index(fields=['can_edit'], name='hosts_hostp_can_edi_2a886d_idx'), models.Index(fields=['can_manage_products'], name='hosts_hostp_can_man_97675c_idx'), models.Index(fields=['can_review_requests'], name='hosts_hostp_can_rev_9780ba_idx'), models.Index(fields=['can_manage_cloud_users'], name='hosts_hostp_can_man_ebcd88_idx')],
                'unique_together': {('user', 'host')},
            },
        ),
    ]
