# Generated by Django 4.2.27 on 2026-01-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_alter_host_port_delete_hostpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='connection_type',
            field=models.CharField(choices=[('winrm', 'WinRM'), ('ssh', 'SSH'), ('localwinserver', '本地WinServer')], default='winrm', max_length=20, verbose_name='连接类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(default=5985, verbose_name='连接端口'),
        ),
    ]
