# Generated by Django 4.2.27 on 2026-04-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0009_host_tunnel_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='host_type',
        ),
    ]
