# Generated by Django 4.2.27 on 2026-05-15 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery任务ID')),
                ('records_pushed', models.IntegerField(default=0, verbose_name='推送记录数')),
                ('records_skipped', models.IntegerField(default=0, verbose_name='跳过记录数')),
                ('records_failed', models.IntegerField(default=0, verbose_name='失败记录数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_push_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Beta推送日志',
                'verbose_name_plural': 'Beta推送日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='beta_push_s_user_id_29a2ce_idx'), models.Index(fields=['status'], name='beta_push_s_status_7d5027_idx')],
            },
        ),
    ]
